//トップページ

import Head from "next/head";
import { useRouter } from 'next/router';

const Home = () => {
  const router = useRouter();

  return (
    <>
    <Head>
        <title>クイズアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <div>
      <h1>クイズアプリ</h1>
      <button onClick={() => router.push('/quiz')}>スタート！</button>
    </div>
    </>
  );
};

export default Home;
