//トップページ

import Head from "next/head";
import { useRouter } from "next/router";
import { useDispatch } from "react-redux";
import { resetQuiz } from "@/store/quizSlice";

const Home = () => {
  const router = useRouter();
  const dispatch = useDispatch(); // ディスパッチをするために使用

  const startQuiz = () => {
    dispatch(resetQuiz());
    router.push("/quiz");
  };

  return (
    <>
      <Head>
        <title>クイズアプリ</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <h1>クイズアプリ</h1>
        <button onClick={startQuiz}>スタート！</button>
      </div>
    </>
  );
};

export default Home;
